### ISSUE TITLE
Recalculate homography for camera

### ISSUE THREAD

**Issue by nicholaschan23** [UTNuclearRobotics/utexas_sterling#32]
- Place chessboard on the floor in front of robot
  - Get measurement of its center relative to the camera
  - *Get all 4 corners*, check through RViz
- Take picture with camera
- Record camera info data

**Comment by nicholaschan23** [comment]
Camera info topic for Oak D
```
header:
  stamp:
    sec: 1733262111
    nanosec: 319031668
  frame_id: oak_rgb_camera_optical_frame
height: 720
width: 1280
distortion_model: rational_polynomial
d:
- -4.01852560043335
- 62.40776824951172
- 0.0007552704191766679
- 0.00017194128304254264
- 9.34029769897461
- -3.8660478591918945
- 61.620399475097656
- 23.798885345458984
k:
- 759.8603515625
- 0.0
- 637.9826049804688
- 0.0
- 759.8603515625
- 358.5901794433594
- 0.0
- 0.0
- 1.0
r:
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
p:
- 759.8603515625
- 0.0
- 637.9826049804688
- 0.0
- 0.0
- 759.8603515625
- 358.5901794433594
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: false
```
